format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$nodejs\
$aws\
$lua\
$jobs\
$docker_context\
$cmd_duration\
$c\
$rust\
$swift\
$zig\
$golang\
$line_break\
$character"""

add_newline = true
palette = 'nord'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[fill]
symbol = ' '

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'
#command_timeout = 1000

[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'

[palettes.onedark]
dark_blue='#61afef'
blue='#56b6c2'
red='#e06c75'
green='#98c379'
purple='#c678dd'
cyan='#56b6c2'
orange='#be5046'
yellow='#e5c07b'
gray='#828997'
white ='#abb2bf'
black='#2c323c'

